package com.mrjaffesclass.apcs.mvc.Othello;
import com.mrjaffesclass.apcs.messenger.*;
import javax.swing.ImageIcon;
import java.net.URL;
/**
 * MVC Template
 * This is a template of an MVC framework used by APCS for the 
 * LandMine project (and others)
 * @author Roger Jaffe
 * @version 1.0
 * 
 */
public class View extends javax.swing.JFrame implements MessageHandler {

  private final Messenger mvcMessaging;
  
  /**
   * Creates a new view
   * @param messages mvcMessaging object
   */
  public View(Messenger messages) {
    mvcMessaging = messages;   // Save the calling controller instance
    initComponents();           // Create and init the GUI components
  }
  
  /**
   * Initialize the model here and subscribe
   * to any required messages
   */
  public void init() {
    // Subscribe to messages here
    ImageIcon blackPiece = new ImageIcon(getClass().getResource("blackPiece.png"));
    ImageIcon whitePiece = new ImageIcon(getClass().getResource("whitePiece.png"));
    ImageIcon legalMove = new ImageIcon(getClass().getResource("legalMove.png"));
    ImageIcon blank = new ImageIcon(getClass().getResource("blank.png"));
    
  }
  
  @Override
  public void messageHandler(String messageName, Object messagePayload) {
    if (messagePayload != null) {
      System.out.println("MSG: received by view: "+messageName+" | "+messagePayload.toString());
    } else {
      System.out.println("MSG: received by view: "+messageName+" | No data sent");
    }
    
  }

  /**
   * Instantiate an object with the field number that was clicked (1 or 2) and
   * the direction that the number should go (up or down)
   * @param fieldNumber 1 or 2 for the field being modified
   * @param direction this.UP (1) or this.DOWN (-1), constants defined above
   * @return the HashMap payload to be sent with the message
   */
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton65 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton5);

        jButton6.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton7);

        jButton8.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton8);

        jButton9.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton9);

        jButton10.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton10);

        jButton11.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton11);

        jButton12.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton12);

        jButton13.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton13);

        jButton14.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton14);

        jButton15.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton15);

        jButton16.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton16);

        jButton17.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton17);

        jButton18.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton18);

        jButton19.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton19);

        jButton20.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton20);

        jButton21.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton21);

        jButton22.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton22);

        jButton23.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton23);

        jButton24.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton24);

        jButton25.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton25);

        jButton26.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton26);

        jButton27.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton27);

        jButton28.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton28);

        jButton29.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton29);

        jButton30.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton30);

        jButton31.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton31);

        jButton32.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton32);

        jButton33.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton33);

        jButton34.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton34);

        jButton35.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton35);

        jButton36.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton36);

        jButton37.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton37);

        jButton38.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton38);

        jButton39.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton39);

        jButton40.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton40);

        jButton41.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton41);

        jButton42.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton42);

        jButton43.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton43);

        jButton44.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton44);

        jButton45.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton45);

        jButton46.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton46);

        jButton47.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton47);

        jButton48.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton48);

        jButton49.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton49);

        jButton50.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton50);

        jButton51.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton51);

        jButton52.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton52);

        jButton53.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton53);

        jButton54.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton54);

        jButton55.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton55);

        jButton56.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton56);

        jButton57.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton57);

        jButton58.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton58);

        jButton59.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton59);

        jButton60.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton60);

        jButton61.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton61);

        jButton62.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton62);

        jButton63.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton63);

        jButton64.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jButton64);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Othello!!!");

        jLabel1.setText("White Counter:");

        jLabel2.setText("Black Counter:");

        jButton65.setText("New Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton65)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2))
                    .addComponent(jLabel12))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton65))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
